import esbuild from "esbuild";
import process from "process";
import { builtinModules } from "node:module";
import fs from "fs";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

const context = await esbuild.context({
  banner: {
    js: banner,
  },
  entryPoints: ["src/main.ts"],
  bundle: true,
  metafile: prod, // 1. Enable metafile generation
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtinModules,
  ],
  format: "cjs",
  target: "es2018",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outfile: "main.js",
  minify: prod,
});

if (prod) {
  const result = await context.rebuild();

  // 3. Write the metafile to disk
  if (result.metafile) {
    fs.writeFileSync("meta.json", JSON.stringify(result.metafile));
    console.log("Analysis metafile generated: meta.json");
  }

  process.exit(0);
} else {
  await context.watch();
}
